### ISSUE TITLE
AD authentication giving me error : binding user: [user] 

### ISSUE THREAD

**Issue by alokkumar0009** [nishen/nginx-ad-proxy#2]
Hiya Admin,

I am trying your code to authenticate my user via AWS managed AD. Normal file based authentication is working fine but when trying to authenticate user via AD, it giving below error:

[2023-11-15 10:55:34,488][DEBUG]: users: ['user1, 'user2']
[2023-11-15 10:55:34,488][DEBUG]: groups: ['users']
[2023-11-15 10:55:34,489][DEBUG]: binding user: [user1]
[2023-11-15 10:55:34,496][ERROR]: binding user failed: [user1] (None)
[2023-11-15 10:55:34,496][INFO]: user1 is not authenticated

I have checked connection from my host to AWS managed AD via Telnet command and , it says connected. Not sure what else I can check.
Any help would be appreciated. 

Thanks

**Comment by nishen** [comment]
There seems to be some issue around line 51 to 65 of:
active_directory_dao.py

Are these variables set correctly? What port are you using?
AD_HOST = os.environ["AD_HOST"]
AD_PORT = os.environ["AD_PORT"]
AD_DOMAIN = os.environ["AD_DOMAIN"]
AD_BASEDN = os.environ["AD_BASEDN"]

**Comment by alokkumar0009** [comment]
all the variables are correct, I am using port 389.
My doubt is around line 49 where trying to establish connection. Here we are using username and password. 
Also at line 82 we are trying to authenticate username. How can both user name are same.

user which is getting used for making connection should be having some additional privilege ? and it should not be same which I am trying to autheticate? 
Is my understanding correct?

Thanks

**Comment by nishen** [comment]
The username and password used is the one passed in via the Basic Authentication header. There is no other user that 'binds' to the AD to then authenticates. This uses the credentials provided to bind as the user directly.

Line 81 is using the already established connection to perform a search. It searches for the logged in user and extracts their group memberships...

Are you able to login to your AWS AD with any other tool? Try Apache Directory Studio (https://directory.apache.org/studio/)
