### ISSUE TITLE
Proxy_pass issues

### ISSUE THREAD

**Issue by fgbona** [nishen/nginx-ad-proxy#3]
Hi Nishen,

Congratulations on the project.

I would like to apply the ad authentication in a host that is already been under a reverse proxy. My configuration is this:

upstream production {
 ip_hash;
 server 10.10.10.10;
}

  location / {
    proxy_cookie_flags ~ secure samesite=strict;
    proxy_set_header Host 'production.company.local';
    proxy_pass http://production;
  }

Is there a way to insert the authentication in this context? Thank you

**Comment by nishen** [comment]
Hi there,

If I understand this correctly, should absoloutely be able to do that. In fact the standard model for it working is exactly this. The example configuration gives you this scenario as well.

**Comment by fgbona** [comment]
Yes, you right. I didn't notice that. Thank you
