### ISSUE TITLE
Duo / Okta Integration

### ISSUE THREAD

**Issue by fgbona** [nishen/nginx-ad-proxy#5]
Hello @nishen 

In your backlog, are there any expectations to integrate with Duo / Okta as a multi-factor authentication?

Thank you

**Comment by nishen** [comment]
Hi @fgbona,

Unfortunately not. This project was designed around pointing to an AD for LDAP based auth which is a common use case. To authn/z against something like Okta there are other projects out there that cater for that.

[Vouch Proxy](https://github.com/vouch/vouch-proxy) is one I actually use for autenticating against Okta which can include MFA from the Okta end. However, this supports a large number of other backends as well.

It works in the same way as this project as well...
